stdlib: fix compilation errors in stdlib
All of them caused by unbound casting diagnostic.
Under `--debug` there are quite a few errors reported:
E.g., on atomic swaps, ispc reported:
Error: Unable to find any matching overload for call to function
(/*unbound*/ int64 * uniform, varying int64)